extends: airbnb-base
rules:
    comma-dangle:
        - error
        - arrays: always-multiline
          objects: always-multiline
          imports: never
          functions: ignore
    import/no-extraneous-dependencies: 0
    indent:
        - error
        - 4
    no-use-before-define: 0
