version: '2'
services:
    wordpress:
        image: dsifford/wordpress:apache-next
        links:
            - db
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./dist:/app/wp-content/plugins/academic-bloggers-toolkit
        environment:
            VERBOSE: 'true'
            DB_NAME: wordpress
            DB_PASS: root
            WP_DEBUG: 'true'
            PLUGINS: >-
                [local]academic-bloggers-toolkit,
                co-authors-plus,
                log-deprecated-notices,
                piglatin,
                query-monitor,
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
