version: '2'
services:
    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 4444:4444
        links:
            - wordpress
    # chrome:
    #     image: selenium/node-chrome
    #     links:
    #         - selenium
    #     depends_on:
    #         - selenium
    #     environment:
    #         - no_proxy=""
    #         - HUB_PORT_4444_TCP_ADDR=selenium
    wordpress:
        image: dsifford/wordpress
        links:
            - db
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./dist:/app/wp-content/plugins/academic-bloggers-toolkit
        environment:
            DB_NAME: wordpress
            DB_PASS: root
            WP_DEBUG: 'true'
            PLUGINS: >-
                co-authors-plus,
                log-deprecated-notices,
                piglatin,
                query-monitor
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
