export enum DialogType {
    ADD = 'ADD',
    EDIT = 'EDIT',
    IMPORT = 'IMPORT',
    NONE = '',
}

export enum MenuActionType {
    CHANGE_STYLE = 'CHANGE_STYLE',
    DESTROY_PROCESSOR = 'DESTROY_PROCESSOR',
    INSERT_STATIC_BIBLIOGRAPHY = 'INSERT_STATIC_BIBLIOGRAPHY',
    OPEN_IMPORT_DIALOG = 'OPEN_IMPORT_DIALOG',
    REFRESH_PROCESSOR = 'REFRESH_PROCESSOR',
}

export const manualPersonObj: Readonly<ABT.Contributor> = {
    type: 'author',
    given: '',
    family: '',
    literal: '',
};

/**
 * Empty object for holding the field data for manual input
 * @note - The following fields were skipped:
 *   - type
 *   - categories
 *   - Person Fields (author, collection-editor, composer, container-author,
 *     director, editor, editorial-director, interfiewer, illustrator,
 *     original-author, recipient, reviewed-author, translator)
 *   - Date Fields (container, original-date, submitted)
 *   - abstract
 *   - annote
 *   - archive-location
 *   - archive-place
 *   - dimensions
 *   - first-reference-note-number
 *   - keyword
 *   - locator
 *   - note
 *   - references
 *   - reviewed-title
 *   - scale
 */
export const manualDataObj: any = {
    DOI: '',
    ISBN: '',
    ISSN: '',
    PMCID: '',
    PMID: '',
    URL: '',
    accessed: '',
    authority: '',
    'call-number': '',
    'chapter-number': '',
    'citation-label': '',
    'citation-number': '',
    'collection-number': '',
    'collection-title': '',
    'container-title': '',
    'container-title-short': '',
    edition: '',
    event: '',
    'event-date': '',
    'event-place': '',
    genre: '',
    id: '0',
    issue: '',
    issued: '',
    journalAbbreviation: '',
    jurisdiction: '',
    language: '',
    medium: '',
    number: '',
    'number-of-pages': '',
    'number-of-volumes': '',
    'original-publisher': '',
    'original-publisher-place': '',
    'original-title': '',
    page: '',
    'page-first': '',
    publisher: '',
    'publisher-place': '',
    section: '',
    shortTitle: '',
    source: '',
    status: '',
    title: '',
    'title-short': '',
    type: 'article-journal',
    version: '',
    volume: '',
    'year-suffix': '',
};

interface LocaleMapper {
    [k: string]: string | undefined;
}

/**
 * This object converts the locale names in wordpress or PubMed (keys) to the locales
 * in CSL (values). If CSL doesn't have a locale for a given WordPress locale,
 * then undefined is used (which will default to en-US)
 */
export const localeMapper: LocaleMapper = {
    af: 'af-ZA',
    'af-ZA': 'af-ZA',
    afr: 'af-ZA',
    ak: undefined,
    alb: undefined,
    am: undefined,
    amh: undefined,
    ar: 'ar',
    'ar-AR': 'ar',
    ara: 'ar',
    arm: undefined,
    arq: 'ar',
    art_xemoji: 'ar',
    ary: 'ar',
    as: 'en-US',
    az: 'tr-TR',
    az_TR: 'tr-TR',
    azb: 'en-US',
    ba: undefined,
    bal: undefined,
    bcc: undefined,
    bel: undefined,
    ben: undefined,
    'bg-BG': 'bg-BG',
    bg_BG: 'bg-BG',
    bn_BD: 'en-US',
    bo: undefined,
    bos: undefined,
    bre: undefined,
    bs_BA: undefined,
    bul: 'bg-BG',
    ca: 'ca-AD',
    'ca-AD': 'ca-AD',
    cat: 'ca-AD',
    ceb: undefined,
    chi: 'zh-CN',
    ckb: undefined,
    co: undefined,
    'cs-CZ': 'cs-CZ',
    cs_CZ: 'cs-CZ',
    cy: 'cy-GB',
    cze: 'cs-CZ',
    'da-DK': 'da-DK',
    da_DK: 'da-DK',
    dan: 'da-DK',
    'de-AT': 'de-AT',
    'de-CH': 'de-CH',
    'de-DE': 'de-DE',
    de_CH: 'de-CH',
    de_DE: 'de-DE',
    dut: 'nl-NL',
    dv: undefined,
    dzo: undefined,
    el: 'el-GR',
    'el-GR': 'el-GR',
    'en-GB': 'en-GB',
    'en-US': 'en-US',
    en_AU: 'en-US',
    en_CA: 'en-US',
    en_GB: 'en-GB',
    en_NZ: 'en-US',
    en_US: 'en-US',
    en_ZA: 'en-US',
    eng: 'en-US',
    eo: undefined,
    epo: undefined,
    'es-AR': 'es-ES',
    'es-CL': 'es-CL',
    'es-ES': 'es-ES',
    'es-MX': 'es-MX',
    es_AR: 'es-ES',
    es_CL: 'es-CL',
    es_CO: 'es-CL',
    es_ES: 'es-ES',
    es_GT: 'es-ES',
    es_MX: 'es-MX',
    es_PE: 'es-CL',
    es_PR: 'es-CL',
    es_VE: 'es-CL',
    est: 'et-ET',
    et: 'et-ET',
    'et-ET': 'et-ET',
    eu: 'eu',
    'fa-IR': 'fa-IR',
    fa_AF: 'fa-IR',
    fa_IR: 'fa-IR',
    fi: 'fi-FI',
    'fi-FI': 'fi-FI',
    fin: 'fi-FI',
    fo: undefined,
    'fr-CA': 'fr-CA',
    'fr-FR': 'fr-FR',
    fr_BE: 'fr-FR',
    fr_CA: 'fr-CA',
    fr_FR: 'fr-FR',
    fre: 'fr-FR',
    frp: undefined,
    fuc: undefined,
    fur: undefined,
    fy: undefined,
    ga: undefined,
    gd: undefined,
    geo: undefined,
    ger: 'de-DE',
    gl_ES: undefined,
    gla: undefined,
    gn: undefined,
    gre: 'el-GR',
    gsw: 'de-CH',
    gu: undefined,
    haw_US: 'en-US',
    haz: undefined,
    'he-IL': 'he-IL',
    he_IL: 'he-IL',
    heb: 'he-IL',
    hi_IN: undefined,
    hin: undefined,
    hr: 'hr-HR',
    'hr-HR': 'hr-HR',
    hrv: 'hr-HR',
    'hu-HU': 'hu-HU',
    hu_HU: 'hu-HU',
    hun: 'hu-HU',
    hy: undefined,
    ice: 'is-IS',
    'id-ID': 'id-ID',
    id_ID: 'id-ID',
    ido: undefined,
    ind: 'id-ID',
    'is-IS': 'is-IS',
    is_IS: 'is-IS',
    'it-IT': 'it-IT',
    it_IT: 'it-IT',
    ita: 'it-IT',
    ja: 'ja-JP',
    'ja-JP': 'ja-JP',
    jpn: 'ja-JP',
    jv_ID: undefined,
    ka_GE: undefined,
    kab: undefined,
    kal: undefined,
    kin: undefined,
    kk: undefined,
    km: 'km-KH',
    'km-KH': 'km-KH',
    kn: undefined,
    'ko-KR': 'ko-KR',
    ko_KR: 'ko-KR',
    kor: 'ko-KR',
    ky_KY: undefined,
    lat: undefined,
    lav: 'lv-LV',
    lb_LU: 'lt-LT',
    li: undefined,
    lin: undefined,
    lit: 'lt-LT',
    lo: undefined,
    'lt-LT': 'lt-LT',
    lt_LT: 'lt-LT',
    lv: 'lv-LV',
    'lv-LV': 'lv-LV',
    mac: undefined,
    mao: undefined,
    may: undefined,
    me_ME: undefined,
    mg_MG: undefined,
    mk_MK: undefined,
    ml_IN: undefined,
    mn: 'mn-MN',
    'mn-MN': 'mn-MN',
    mr: undefined,
    mri: undefined,
    ms_MY: undefined,
    mul: undefined,
    my_MM: undefined,
    'nb-NO': 'nb-NO',
    nb_NO: 'nb-NO',
    ne_NP: undefined,
    nl: 'nl-NL',
    'nl-NL': 'nl-NL',
    nl_BE: 'nl-NL',
    nl_NL: 'nl-NL',
    'nn-NO': 'nn-NO',
    nn_NO: 'nn-NO',
    nor: 'nn-NO',
    oci: undefined,
    ory: undefined,
    os: undefined,
    pa_IN: undefined,
    per: 'fa-IR',
    'pl-PL': 'pl-PL',
    pl_PL: 'pl-PL',
    pol: 'pl-PL',
    por: 'pt-PT',
    ps: undefined,
    'pt-BR': 'pt-BR',
    'pt-PT': 'pt-PT',
    pt_BR: 'pt-BR',
    pt_PT: 'pt-PT',
    rhg: undefined,
    'ro-RO': 'ro-RO',
    ro_RO: 'ro-RO',
    roh: undefined,
    'ru-RU': 'ru-RU',
    ru_RU: 'ru-RU',
    rue: undefined,
    rum: 'ro-RO',
    rup_MK: undefined,
    rus: 'ru-RU',
    sa_IN: undefined,
    sah: undefined,
    san: undefined,
    si_LK: undefined,
    'sk-SK': 'sk-SK',
    sk_SK: 'sk-SK',
    'sl-SI': 'sl-SI',
    sl_SI: 'sl-SI',
    slo: 'sk-SK',
    slv: 'sl-SI',
    snd: undefined,
    so_SO: undefined,
    spa: 'es-ES',
    sq: undefined,
    'sr-RS': 'sr-RS',
    sr_RS: 'sr-RS',
    srd: undefined,
    srp: 'sr-RS',
    su_ID: undefined,
    'sv-SE': 'sv-SE',
    sv_SE: 'sv-SE',
    sw: undefined,
    swe: 'sv-SE',
    szl: undefined,
    ta_IN: undefined,
    ta_LK: undefined,
    tah: undefined,
    te: undefined,
    tg: undefined,
    th: 'th-TH',
    'th-TH': 'th-TH',
    tha: 'th-TH',
    tir: undefined,
    tl: undefined,
    'tr-TR': 'tr-TR',
    tr_TR: 'tr-TR',
    tt_RU: undefined,
    tuk: undefined,
    tur: 'tr-TR',
    twd: undefined,
    tzm: undefined,
    ug_CN: undefined,
    uk: 'uk-UA',
    'uk-UA': 'uk-UA',
    ukr: 'uk-UA',
    und: undefined,
    ur: undefined,
    urd: undefined,
    uz_UZ: undefined,
    vi: 'vi-VN',
    'vi-VN': 'vi-VN',
    vie: 'vi-VN',
    wa: undefined,
    wel: undefined,
    xmf: undefined,
    yor: undefined,
    'zh-CN': 'zh-CN',
    'zh-TW': 'zh-TW',
    zh_CN: 'zh-CN',
    zh_HK: 'zh-CN',
    zh_TW: 'zh-TW',
};
