export const ADD_CITATION = 'ADD_CITATION';
export const REMOVE_CITATION = 'REMOVE_CITATION';
export const MOVE_CITATION = 'MOVE_CITATION';

export const ADD_TO_SELECTION = 'ADD_TO_SELECTION';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
