export const enum Actions {
    CLEAR_SELECTED_ITEMS = 'CLEAR_SELECTED_ITEMS',
    SET_IDENTIFIER_KIND = 'SET_IDENTIFIER_KIND',
    SET_SIDEBAR_SORT_MODE = 'SET_SIDEBAR_SORT_MODE',
    SET_SIDEBAR_SORT_ORDER = 'SET_SIDEBAR_SORT_ORDER',
    TOGGLE_ITEM_SELECTED = 'TOGGLE_ITEM_SELECTED',
}
