export const ABT_wp: BackendGlobals.ABT_wp = {
    abt_url: 'http://localhost:8080/wp-content/plugins/academic-bloggers-toolkit',
    home_url: 'http://localhost:8080',
    plugins_url: 'http://localhost:8080/wp-content/plugins',
    wp_upload_dir: {
        basedir: '/app/wp-content/uploads',
        baseurl: 'http://localhost:8080/wp-content/uploads',
        error: false,
        path: '/app/wp-content/uploads/2017/08',
        subdir: '/2017/08',
        url: 'http://localhost:8080/wp-content/uploads/2017/08',
    },
    info: {
        site: {
            language: 'en_US',
            name: 'Test Site',
            plugins: ['academic-bloggers-toolkit'],
            theme: 'twentyseventeen',
            url: 'http://localhost:8080',
        },
        versions: {
            abt: '0.0.0',
            php: '0.0.0',
            wordpress: '0.0.0',
        },
    },
};

export const ABT_Reflist_State: BackendGlobals.ABT_Reflist_State = {
    bibOptions: {
        heading: 'Bibliography',
        style: 'fixed',
        headingLevel: 'h3',
    },
    cache: {
        style: 'american-medical-association',
        links: 'always',
        locale: 'en-US',
    },
    citationByIndex: [
        {
            citationID: 'htmlSpanId',
            citationItems: [
                {
                    id: 'aaaaaaaa',
                    item: {
                        ISSN: '3',
                        PMID: '12345',
                        URL: 'http://www.test.com',
                        author: [{ family: 'Doe', given: 'JD' }],
                        'chapter-number': '1',
                        'container-title-short': 'J Test',
                        'container-title': 'Journal of Testing',
                        edition: '2',
                        id: 'aaaaaaaa',
                        issue: '4',
                        issued: { 'date-parts': [['2016', '08', '19']] },
                        journalAbbreviation: 'J Test',
                        language: 'en-US',
                        medium: 'print',
                        number: '5',
                        page: '100-3',
                        'publisher-place': 'USA',
                        publisher: 'Test',
                        title: 'Test Title',
                        type: 'article-journal',
                        volume: '6',
                    },
                },
                {
                    id: 'bbbbbbbb',
                    item: {
                        ISSN: '3',
                        PMID: '12345',
                        URL: 'http://www.test.com',
                        author: [{ family: 'Doe', given: 'JD' }],
                        'chapter-number': '1',
                        'container-title-short': 'J Test',
                        'container-title': 'Journal of Testing',
                        edition: '2',
                        id: 'bbbbbbbb',
                        issue: '4',
                        issued: { 'date-parts': [['2016', '08', '19']] },
                        journalAbbreviation: 'J Test',
                        language: 'en-US',
                        medium: 'print',
                        number: '5',
                        page: '100-3',
                        'publisher-place': 'USA',
                        publisher: 'Test',
                        title: 'Test Title',
                        type: 'article-journal',
                        volume: '6',
                    },
                },
            ],
            properties: {},
        },
        {
            citationID: 'otherHtmlSpanId',
            citationItems: [
                {
                    id: 'bbbbbbbb',
                    item: {
                        ISSN: '3',
                        PMID: '12345',
                        URL: 'http://www.test.com',
                        author: [{ family: 'Doe', given: 'JD' }],
                        'chapter-number': '1',
                        'container-title-short': 'J Test',
                        'container-title': 'Journal of Testing',
                        edition: '2',
                        id: 'bbbbbbbb',
                        issue: '4',
                        issued: { 'date-parts': [['2016', '08', '19']] },
                        journalAbbreviation: 'J Test',
                        language: 'en-US',
                        medium: 'print',
                        number: '5',
                        page: '100-3',
                        'publisher-place': 'USA',
                        publisher: 'Test',
                        title: 'Other Test Title',
                        type: 'article-journal',
                        volume: '6',
                    },
                },
            ],
            properties: {},
        },
    ],
    CSL: {
        aaaaaaaa: {
            ISSN: '3',
            PMID: '12345',
            URL: 'http://www.test.com',
            author: [{ family: 'Doe', given: 'JD' }],
            'chapter-number': '1',
            'container-title-short': 'J Test',
            'container-title': 'Journal of Testing',
            edition: '2',
            id: 'aaaaaaaa',
            issue: '4',
            issued: { 'date-parts': [['2016', '08', '19']] },
            journalAbbreviation: 'J Test',
            language: 'en-US',
            medium: 'print',
            number: '5',
            page: '100-3',
            'publisher-place': 'USA',
            publisher: 'Test',
            title: 'Test Title',
            type: 'article-journal',
            volume: '6',
        },
        bbbbbbbb: {
            ISSN: '3',
            PMID: '12345',
            URL: 'http://www.test.com',
            author: [{ family: 'Doe', given: 'JD' }],
            'chapter-number': '1',
            'container-title-short': 'J Test',
            'container-title': 'Journal of Testing',
            edition: '2',
            id: 'bbbbbbbb',
            issue: '4',
            issued: { 'date-parts': [['2016', '08', '19']] },
            journalAbbreviation: 'J Test',
            language: 'en-US',
            medium: 'print',
            number: '5',
            page: '100-3',
            'publisher-place': 'USA',
            publisher: 'Test',
            title: 'Other Test Title',
            type: 'article-journal',
            volume: '6',
        },
        cccccccc: {
            ISSN: '3',
            PMID: '12345',
            URL: 'http://www.test.com',
            author: [{ family: 'Doe', given: 'JD' }],
            'chapter-number': '1',
            'container-title-short': 'J Test',
            'container-title': 'Journal of Testing',
            edition: '2',
            id: 'cccccccc',
            issue: '4',
            issued: { 'date-parts': [['2016', '08', '19']] },
            journalAbbreviation: 'J Test',
            language: 'en-US',
            medium: 'print',
            number: '5',
            page: '100-3',
            'publisher-place': 'USA',
            publisher: 'Test',
            title: 'Test Title Uncited',
            type: 'article-journal',
            volume: '6',
        },
    },
};

export const ABT_i18n: BackendGlobals.ABT_i18n = {
    misc: {
        footnotes: 'Footnotes',
    },
    referenceList: {
        tooltips: {
            insert: 'Insert selected references',
            add: 'Add reference',
            remove: 'Remove selected references',
            pin: 'Pin reference list',
        },
        citedItems: 'Cited Items',
        uncitedItems: 'Uncited Items',
        menu: {
            styleLabels: {
                custom: 'Custom Style',
                predefined: 'Pre-defined Styles',
            },
            toggleLabel: 'Toggle menu',
            tooltips: {
                importRIS: 'Import references',
                refresh: 'Refresh reference list',
                destroy: 'Delete all references',
                help: 'Usage instructions',
                staticPubList: 'Insert static publication list',
            },
        },
    },
    dialogs: {
        closeLabel: 'Close dialog',
        edit: {
            title: 'Edit Reference',
            confirm: 'Confirm',
        },
        import: {
            title: 'Import References',
            upload: 'Choose File',
            importBtn: 'Import',
        },
        pubmed: {
            title: 'Search PubMed',
            search: 'Search',
            next: 'Next',
            previous: 'Previous',
            addReference: 'Select',
            viewReference: 'View',
        },
        add: {
            title: 'Add References',
            people: {
                add: 'Add Contributor',
                contributors: 'Contributors',
                surname: 'Surname',
                given: 'Given Name, M.I.',
            },
            manualEntryContainer: {
                citationType: 'Citation Type',
                autocite: 'Autocite',
                URL: 'URL',
                ISBN: 'ISBN',
                search: 'Search',
            },
            identifierInput: {
                label: 'DOI/PMID/PMCID',
            },
            buttonRow: {
                addManually: 'Add Manually',
                addWithIdentifier: 'Add with Identifier',
                searchPubmed: 'Search PubMed',
                addReference: 'Add Reference',
                insertInline: 'Insert citation inline',
            },
        },
    },
    errors: {
        badRequest: 'Request not valid',
        denied: 'Site denied request',
        fileExtensionError: 'Invalid file extension. Extension must be .ris, .bib, or .bibtex',
        filetypeError: 'The file could not be processed',
        identifiersNotFound: {
            all: 'No identifiers could be found for your request',
            some: 'The following identifiers could not be found',
        },
        prefix: 'Error',
        networkError: 'Network Error',
        noResults: 'Your search returned 0 results',
        risLeftovers: 'The following references were unable to be processed',
        statusError: 'Request returned a non-200 status code',
        warnings: {
            warning: 'Warning',
            reason: 'Reason',
            noBib: {
                message: 'Cannot create publication list for currently selected citation style',
                reason: 'Style does not include bibliography',
            },
        },
        unexpected: {
            message: 'An unexpected error occurred',
            reportInstructions:
                'Please report this error, including the steps taken to trigger it, here: \nhttps://github.com/dsifford/academic-bloggers-toolkit/issues',
        },
    },
    fieldmaps: {
        bill: {
            title: 'Bill',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number',
                    label: 'Bill Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Code Pages',
                    required: false,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (e.g. 100-200)',
                },
                {
                    value: 'volume',
                    label: 'Code Volume',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'section',
                    label: 'Section',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Legislative Body',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Sponsor',
                },
            ],
        },
        book: {
            title: 'Book',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'collection-title',
                    label: 'Series Title',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'collection-number',
                    label: 'Series Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'number-of-pages',
                    label: '# of Pages',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'volume',
                    label: 'Volume',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'edition',
                    label: 'Edition',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Publisher',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher-place',
                    label: 'Publisher Location',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
                {
                    type: 'collection-editor',
                    label: 'Series Editor',
                },
                {
                    type: 'translator',
                    label: 'Translator',
                },
            ],
        },
        chapter: {
            title: 'Book Section',
            fields: [
                {
                    value: 'title',
                    label: 'Section Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Book Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'chapter-number',
                    label: 'Chapter Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'collection-title',
                    label: 'Series',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'collection-number',
                    label: 'Series Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'volume',
                    label: 'Volume',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number-of-volumes',
                    label: '# of Volumes',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'edition',
                    label: 'Edition',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Publisher',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher-place',
                    label: 'Publisher Location',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'ISBN',
                    label: 'ISBN',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Section Author',
                },
                {
                    type: 'container-author',
                    label: 'Book Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
                {
                    type: 'collection-editor',
                    label: 'Series Editor',
                },
                {
                    type: 'translator',
                    label: 'Translator',
                },
            ],
        },
        broadcast: {
            title: 'Broadcast',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: false,
                    pattern: '.*',
                    placeholder: 'E.g. "Chapter 1"',
                },
                {
                    value: 'container-title',
                    label: 'Program Title',
                    required: true,
                    pattern: '.*',
                    placeholder: 'E.g. "House of Cards"',
                },
                {
                    value: 'number',
                    label: 'Episode Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'medium',
                    label: 'Format',
                    required: false,
                    pattern: '.*',
                    placeholder: 'E.g. "Television"',
                },
                {
                    value: 'publisher',
                    label: 'Network',
                    required: true,
                    pattern: '.*',
                    placeholder: 'E.g. "Netflix"',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Producer',
                },
                {
                    type: 'director',
                    label: 'Director',
                },
            ],
        },
        legal_case: {
            title: 'Case',
            fields: [
                {
                    value: 'title',
                    label: 'Case Name',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'authority',
                    label: 'Court',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number',
                    label: 'Docket Number',
                    required: false,
                    pattern: 'S.*', // eslint-disable-line
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
            ],
        },
        'paper-conference': {
            title: 'Conference Proceeding',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'event',
                    label: 'Conference Name',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher-place',
                    label: 'Conference Location',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
                {
                    type: 'collection-editor',
                    label: 'Series Editor',
                },
                {
                    type: 'translator',
                    label: 'Translator',
                },
            ],
        },
        'entry-encyclopedia': {
            title: 'Encyclopedia Entry',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Encyclopedia Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'collection-title',
                    label: 'Series',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'collection-number',
                    label: 'Series Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'volume',
                    label: 'Volume',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'number-of-volumes',
                    label: '# of Volumes',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'edition',
                    label: 'Edition',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Publisher',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher-place',
                    label: 'Publisher Location',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
                {
                    type: 'collection-editor',
                    label: 'Series Editor',
                },
                {
                    type: 'translator',
                    label: 'Translator',
                },
            ],
        },
        motion_picture: {
            title: 'Film',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Distributor',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'genre',
                    label: 'Genre',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'language',
                    label: 'Language',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'medium',
                    label: 'Format',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Scriptwriter',
                },
                {
                    type: 'director',
                    label: 'Director',
                },
                {
                    type: 'editor',
                    label: 'Producer',
                },
            ],
        },
        article: {
            title: 'Generic (Note)',
            fields: [
                {
                    value: 'title',
                    label: 'Text',
                    required: true,
                    pattern: '.*',
                    placeholder: 'Note: This type may not work with certain citation styles',
                },
            ],
            people: [],
        },
        speech: {
            title: 'Presentation',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'event',
                    label: 'Event Name',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'event-place',
                    label: 'Event Location',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'language',
                    label: 'Language',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(/[0-9]{2})?(/[0-9]{2})?(?!/)$', // eslint-disable-line
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Presenter',
                },
            ],
        },
        'article-journal': {
            title: 'Journal Article',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Journal',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'journalAbbreviation',
                    label: 'Journal Abbreviation',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'volume',
                    label: 'Volume',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'issue',
                    label: 'Issue',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: false,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'DOI',
                    label: 'DOI',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'URL',
                    label: 'URL',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
            ],
        },
        'article-magazine': {
            title: 'Magazine Article',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Magazine',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'volume',
                    label: 'Volume',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'issue',
                    label: 'Issue',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'ISSN',
                    label: 'ISSN',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'URL',
                    label: 'URL',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
            ],
        },
        'article-newspaper': {
            title: 'Newspaper Article',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Publication',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'section',
                    label: 'Section',
                    required: false,
                    pattern: '.*',
                    placeholder: 'E.g. "Sports", "Politics"',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'issue',
                    label: 'Issue',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'URL',
                    label: 'URL',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'editor',
                    label: 'Editor',
                },
            ],
        },
        patent: {
            title: 'Patent',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number',
                    label: 'Number',
                    required: true,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'jurisdiction',
                    label: 'Jurisdiction',
                    required: true,
                    pattern: '.*',
                    placeholder: 'E.g. "United States"',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'publisher',
                    label: 'Issuer',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Inventor',
                },
            ],
        },
        report: {
            title: 'Report',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number',
                    label: 'Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'collection-title',
                    label: 'Series',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Publication',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'Publisher',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'URL',
                    label: 'URL',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
                {
                    type: 'collection-editor',
                    label: 'Series Editor',
                },
                {
                    type: 'translator',
                    label: 'Translator',
                },
            ],
        },
        legislation: {
            title: 'Statute',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number',
                    label: 'Statute Number',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'section',
                    label: 'Section',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'page',
                    label: 'Pages',
                    required: true,
                    pattern: '^[0-9]+-?[0-9]*$',
                    placeholder: 'Number or Range of Numbers (100-200)',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
            ],
        },
        thesis: {
            title: 'Thesis',
            fields: [
                {
                    value: 'title',
                    label: 'Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'number-of-pages',
                    label: '# of Pages',
                    required: false,
                    pattern: '[0-9]+',
                    placeholder: '',
                },
                {
                    value: 'publisher',
                    label: 'University',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'publisher-place',
                    label: 'Location',
                    required: false,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: true,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
            ],
        },
        webpage: {
            title: 'Web Page',
            fields: [
                {
                    value: 'title',
                    label: 'Content Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'container-title',
                    label: 'Website Title',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'URL',
                    label: 'URL',
                    required: true,
                    pattern: '.*',
                    placeholder: '',
                },
                {
                    value: 'issued',
                    label: 'Date',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
                {
                    value: 'accessed',
                    label: 'Date Accessed',
                    required: false,
                    pattern: '[0-9]{4}(\\/[0-9]{2})?(\\/[0-9]{2})?(?!\\/)$',
                    placeholder: 'YYYY/MM/DD or YYYY/MM or YYYY',
                },
            ],
            people: [
                {
                    type: 'author',
                    label: 'Author',
                },
            ],
        },
    },
    citationTypes: [
        {
            label: 'Bill',
            value: 'bill',
        },
        {
            label: 'Book',
            value: 'book',
        },
        {
            label: 'Book Section',
            value: 'chapter',
        },
        {
            label: 'Case',
            value: 'legal_case',
        },
        {
            label: 'Conference Proceeding',
            value: 'paper-conference',
        },
        {
            label: 'Encyclopedia Entry',
            value: 'entry-encyclopedia',
        },
        {
            label: 'Film',
            value: 'motion_picture',
        },
        {
            label: 'Hearing',
            value: 'speech',
        },
        {
            label: 'Journal Article',
            value: 'article-journal',
        },
        {
            label: 'Magazine Article',
            value: 'article-magazine',
        },
        {
            label: 'Newspaper Article',
            value: 'article-newspaper',
        },
        {
            label: 'Patent',
            value: 'patent',
        },
        {
            label: 'Test not in use',
            value: 'testing',
        },
        {
            label: 'Test not in use',
            value: 'testing2',
        },
        {
            label: 'Report',
            value: 'report',
        },
        {
            label: 'Statute',
            value: 'legislation',
        },
        {
            label: 'Thesis',
            value: 'thesis',
        },
        {
            label: 'Television Broadcast',
            value: 'broadcast',
        },
        {
            label: 'Web Page',
            value: 'webpage',
        },
    ],
};
