#!/usr/bin/env python3
"""
Exports translation files from POEditor
"""

from os import environ, path, listdir, remove
import requests

LANG_DIR = path.normpath(path.abspath(path.dirname(__file__)) +
                         '/../src/languages/')
FILE_PREFIX = 'academic-bloggers-toolkit-'
PROJECT_ID = '68585'
TOKEN = environ['PO_EDITOR_TOKEN']
LANGS = {
    'es-ar': [
        'es_AR',
        'es_CL',
        'es_CO',
        'es_GT',
        'es_MX',
        'es_PE',
        'es_ES',
        'es_VE',
    ],
    'de': [
        'de_DE',
        'de_CH',
    ],
}


def get_download_url(language):
    """Retrieve download url from POEditor."""
    req = requests.post(
        'https://poeditor.com/api/',
        data={
            'api_token': TOKEN,
            'action': 'export',
            'id': PROJECT_ID,
            'language': language,
            'type': 'mo',
        })
    res = req.json()
    return res['item']


def download(link, loc):
    """Download file from POEditor and save to disk."""
    with open(LANG_DIR + '/' + FILE_PREFIX + loc + '.mo', "wb") as file:
        response = requests.get(link)
        file.write(response.content)


# Remove all languages
for f in listdir(LANG_DIR):
    remove(LANG_DIR + '/' + f)

# Download files to languages directory
for lang, locales in LANGS.items():
    url = get_download_url(lang)
    for locale in locales:
        download(url, locale)
