// tslint:disable:no-namespace
// Type definitions for WordPress's "wp" namespace

/*~ If your library has properties exposed on a global variable,
 *~ place them here.
 *~ You should also place types (interfaces and type alias) here.
 */
declare namespace wp {
    const codeEditor:
        | {
              initialize(elementId: string, options: object): void;
          }
        | undefined;

    type Dashicon =
        | 'admin-appearance'
        | 'admin-collapse'
        | 'admin-comments'
        | 'admin-customizer'
        | 'admin-generic'
        | 'admin-home'
        | 'admin-links'
        | 'admin-media'
        | 'admin-multisite'
        | 'admin-network'
        | 'admin-page'
        | 'admin-plugins'
        | 'admin-post'
        | 'admin-settings'
        | 'admin-site-alt'
        | 'admin-site-alt2'
        | 'admin-site-alt3'
        | 'admin-site'
        | 'admin-tools'
        | 'admin-users'
        | 'album'
        | 'align-center'
        | 'align-left'
        | 'align-none'
        | 'align-right'
        | 'analytics'
        | 'archive'
        | 'arrow-down-alt'
        | 'arrow-down-alt2'
        | 'arrow-down'
        | 'arrow-left-alt'
        | 'arrow-left-alt2'
        | 'arrow-left'
        | 'arrow-right-alt'
        | 'arrow-right-alt2'
        | 'arrow-right'
        | 'arrow-up-alt'
        | 'arrow-up-alt2'
        | 'arrow-up'
        | 'art'
        | 'awards'
        | 'backup'
        | 'book-alt'
        | 'book'
        | 'buddicons-activity'
        | 'buddicons-buddypress-logo'
        | 'buddicons-community'
        | 'buddicons-forums'
        | 'buddicons-friends'
        | 'buddicons-groups'
        | 'buddicons-pm'
        | 'buddicons-replies'
        | 'buddicons-topics'
        | 'buddicons-tracking'
        | 'buddipress-bbpress-logo'
        | 'building'
        | 'businessman'
        | 'calendar-alt'
        | 'calendar'
        | 'camera'
        | 'carrot'
        | 'cart'
        | 'category'
        | 'chart-area'
        | 'chart-bar'
        | 'chart-line'
        | 'chart-pie'
        | 'clipboard'
        | 'clock'
        | 'cloud'
        | 'controls-back'
        | 'controls-forward'
        | 'controls-pause'
        | 'controls-play'
        | 'controls-repeat'
        | 'controls-skipback'
        | 'controls-skipforward'
        | 'controls-volumeoff'
        | 'controls-volumeon'
        | 'dashboard'
        | 'desktop'
        | 'dismiss'
        | 'download'
        | 'edit'
        | 'editor-aligncenter'
        | 'editor-alignleft'
        | 'editor-alignright'
        | 'editor-bold'
        | 'editor-break'
        | 'editor-code'
        | 'editor-contract'
        | 'editor-customchar'
        | 'editor-expand'
        | 'editor-help'
        | 'editor-indent'
        | 'editor-insertmore'
        | 'editor-italic'
        | 'editor-justify'
        | 'editor-kitchensink'
        | 'editor-ol'
        | 'editor-outdent'
        | 'editor-paragraph'
        | 'editor-paste-text'
        | 'editor-paste-word'
        | 'editor-quote'
        | 'editor-removeformatting'
        | 'editor-rtl'
        | 'editor-spellcheck'
        | 'editor-strikethrough'
        | 'editor-table'
        | 'editor-textcolor'
        | 'editor-ul'
        | 'editor-underline'
        | 'editor-unlink'
        | 'editor-video'
        | 'email-alt'
        | 'email-alt2'
        | 'email'
        | 'excerpt-view'
        | 'external'
        | 'facebook-alt'
        | 'facebook'
        | 'feedback'
        | 'filter'
        | 'flag'
        | 'format-aside'
        | 'format-audio'
        | 'format-chat'
        | 'format-gallery'
        | 'format-image'
        | 'format-quote'
        | 'format-status'
        | 'format-video'
        | 'forms'
        | 'googleplus'
        | 'grid-view'
        | 'groups'
        | 'hammer'
        | 'heart'
        | 'hidden'
        | 'id-alt'
        | 'id'
        | 'image-crop'
        | 'image-filter'
        | 'image-flip-horizontal'
        | 'image-flip-vertical'
        | 'image-rotate-left'
        | 'image-rotate-right'
        | 'image-rotate'
        | 'images-alt'
        | 'images-alt2'
        | 'index-card'
        | 'info'
        | 'laptop'
        | 'layout'
        | 'leftright'
        | 'lightbulb'
        | 'list-view'
        | 'location-alt'
        | 'location'
        | 'lock'
        | 'marker'
        | 'media-archive'
        | 'media-audio'
        | 'media-code'
        | 'media-default'
        | 'media-document'
        | 'media-interactive'
        | 'media-spreadsheet'
        | 'media-text'
        | 'media-video'
        | 'megaphone'
        | 'menu-alt'
        | 'menu'
        | 'microphone'
        | 'migrate'
        | 'minus'
        | 'money'
        | 'move'
        | 'nametag'
        | 'networking'
        | 'no-alt'
        | 'no'
        | 'palmtree'
        | 'paperclip'
        | 'performance'
        | 'phone'
        | 'playlist-audio'
        | 'playlist-video'
        | 'plus-alt'
        | 'plus-light'
        | 'plus'
        | 'portfolio'
        | 'post-status'
        | 'pressthis'
        | 'products'
        | 'randomize'
        | 'redo'
        | 'rss'
        | 'schedule'
        | 'screenoptions'
        | 'search'
        | 'share-alt'
        | 'share-alt2'
        | 'share'
        | 'shield-alt'
        | 'shield'
        | 'slides'
        | 'smartphone'
        | 'smiley'
        | 'sort'
        | 'sos'
        | 'star-empty'
        | 'star-filled'
        | 'star-half'
        | 'sticky'
        | 'store'
        | 'tablet'
        | 'tag'
        | 'tagcloud'
        | 'testimonial'
        | 'text'
        | 'thumbs-down'
        | 'thumbs-up'
        | 'tickets-alt'
        | 'tickets'
        | 'translation'
        | 'trash'
        | 'twitter'
        | 'undo'
        | 'universal-access-alt'
        | 'universal-access'
        | 'unlock'
        | 'update'
        | 'upload'
        | 'vault'
        | 'video-alt'
        | 'video-alt2'
        | 'video-alt3'
        | 'visibility'
        | 'warning'
        | 'welcome-add-page'
        | 'welcome-comments'
        | 'welcome-learn-more'
        | 'welcome-view-site'
        | 'welcome-widgets-menus'
        | 'welcome-write-blog'
        | 'wordpress-alt'
        | 'wordpress'
        | 'yes';
    // //~ We can write 'myLib.timeout = 50;'
    // let timeout: number;

    // //~ We can access 'myLib.version', but not change it
    // const version: string;

    // //~ There's some class we can create via 'let c = new myLib.Cat(42)'
    // //~ Or reference e.g. 'function f(c: myLib.Cat) { ... }
    // class Cat {
    //     constructor(n: number);

    //     //~ We can read 'c.age' from a 'Cat' instance
    //     readonly age: number;

    //     //~ We can invoke 'c.purr()' from a 'Cat' instance
    //     purr(): void;
    // }

    // //~ We can declare a variable as
    // //~   'var s: myLib.CatSettings = { weight: 5, name: "Maru" };'
    // interface CatSettings {
    //     weight: number;
    //     name: string;
    //     tailLength?: number;
    // }

    // //~ We can write 'const v: myLib.VetID = 42;'
    // //~  or 'const v: myLib.VetID = "bob";'
    // type VetID = string | number;

    // //~ We can invoke 'myLib.checkCat(c)' or 'myLib.checkCat(c, v);'
    // function checkCat(c: Cat, s?: VetID);
}
