#!/usr/bin/env python3

import requests
from os import environ, path, listdir, remove

lang_dir = path.normpath(path.abspath(path.dirname(__file__)) +
                         '/../src/languages/')
file_prefix = 'academic-bloggers-toolkit-'
project_id = '68585'
access_token = environ['PO_EDITOR_TOKEN']
languages = {
    'es-ar': ['es_AR', 'es_CL', 'es_CO', 'es_GT',
              'es_MX', 'es_PE', 'es_ES', 'es_VE'],
    'de': ['de_DE', 'de_CH'],
}


def getDownloadUrl(language):
    """Retrieve download url from POEditor."""
    req = requests.post(
        'https://poeditor.com/api/',
        data={
            'api_token': access_token,
            'action': 'export',
            'id': project_id,
            'language': language,
            'type': 'mo',
        })
    res = req.json()
    return res['item']


def download(url, locale):
    """Download file from POEditor and save to disk."""
    with open(lang_dir + '/' + file_prefix + locale + '.mo', "wb") as file:
        response = requests.get(url)
        file.write(response.content)


# Remove all languages
for f in listdir(lang_dir):
    remove(lang_dir + '/' + f)

# Download files to languages directory
for lang, locales in languages.items():
    url = getDownloadUrl(lang)
    for locale in locales:
        download(url, locale)
