declare var ABT_meta;

/**
 * Opens `reference-window.tsx` and returns a promise which resolves to either
 *   `ABT.ReferencePayload` or `null` on close.
 * @param editor   The active TinyMCE instance.
 * @return A Promise which resolves to ABT.ReferenceWindowPayload
 */
export function referenceWindow(editor: TinyMCE.Editor): Promise<ABT.ReferenceWindowPayload> {
    return new Promise((resolve, reject) => {
        editor.windowManager.open({
            title: 'Insert Formatted Reference',
            url: ABT_meta.tinymceViewsURL + 'reference-window.html',
            width: 600,
            height: 10,
            params: {
                baseUrl: ABT_meta.tinymceViewsURL,
            },
            onclose: (e) => {
                if (!e.target.params.data) resolve(null);
                resolve(e.target.params.data as ABT.ReferenceWindowPayload);
            },
        });
    });
};

export function importWindow(editor: TinyMCE.Editor): Promise<ABT.ImportWindowPayload> {
    return new Promise((resolve, reject) => {
        editor.windowManager.open({
            title: 'Import References from RIS File',
            url: ABT_meta.tinymceViewsURL + 'import-window.html',
            width: 600,
            height: 10,
            onclose: (e) => {
                if (!e.target.params.data) resolve(null);
                resolve(e.target.params.data as ABT.ImportWindowPayload);
            },
        });
    });
}

interface CitationPositions {
    /** The index of the HTMLSpanElement being inserted */
    currentIndex: number;
    locations: [Citeproc.CitationsPrePost, Citeproc.CitationsPrePost];
}

/**
 * Iterates the active TinyMCE instance and obtains the citations that come both
 *   before and after the inline citation being inserted currently. Also receives
 *   the index of the current citation within the document (ie, if there's one
 *   citation before and one citation after the current citation, `currentIndex`
 *   will be 1).
 * @param editor The active TinyMCE instance.
 * @return Parsed citation data.
 */
export function getRelativeCitationPositions(editor: TinyMCE.Editor): CitationPositions {
    const selection = editor.selection;
    const doc: Document = editor.dom.doc;

    const cursor = editor.dom.create('span', { id: 'CURSOR', class: 'abt_cite'});
    selection.getNode().appendChild(cursor);

    const citations = doc.getElementsByClassName('abt_cite');
    const payload: CitationPositions = {
        currentIndex: 0,
        locations: [[], []],
    };

    if (citations.length > 1) {
        let key = 0;
        Array.from(citations).forEach((el, i) => {
            if (el.id === 'CURSOR') {
                key = 1;
                payload.currentIndex = i;
                return;
            }
            payload.locations[key].push([el.id, i - key]);
        });
    }
    let el = editor.dom.doc.getElementById('CURSOR');
    el.parentElement.removeChild(el);
    return payload;
}

/**
 * Updates the editor with inline citation data (citation clusters) generated
 *   by the processor.
 *
 * `reparseExisting` is a boolean which represents wheter or not the function
 *   should be inserting a new HTMLSpanElement, or if it just needs to refresh
 *   the current editor state, either due to a style change or on first init
 *   using cached data.
 * @param  editor   Active TinyMCE editor.
 * @param  clusters Citeproc.CitationClusterData[] generated by the processor.
 * @param  citationByIndex CitationByIndex data used to generate data attributes.
 * @param  reparseExisting see above note.
 */
export function parseInlineCitations(
    editor: TinyMCE.Editor,
    clusters: Citeproc.CitationClusterData[],
    citationByIndex: Citeproc.CitationByIndex,
    reparseExisting: boolean = false
): void {
    for (const [i, item] of clusters.entries()) {
        if (i === 0 && !reparseExisting) {
            const sortedItems: Citeproc.SortedItems = citationByIndex[item[0]].sortedItems;
            const idList: string = JSON.stringify(sortedItems.map(c => c[1].id));
            editor.insertContent(
                `<span id='${item[2]}' data-reflist='${idList}' class='abt_cite noselect mceNonEditable'>${item[1]}</span>`
            );
            continue;
        }
        const citation: HTMLSpanElement = editor.dom.doc.getElementById(item[2]);
        citation.innerHTML = item[1];
    }
}

/**
 * Replaces the current bibliography, or creates a new one if one doesn't exist
 * @param editor       Active TinyMCE editor.
 * @param bibliography Bibliography array.
 */
export function setBibliography(
    editor: TinyMCE.Editor,
    bibliography: {id: string, html: string}[],
    options: {heading: string, style: 'fixed'|'toggle'}
): void {
    const doc = editor.dom.doc;
    const existingBib = doc.getElementById('abt-smart-bib');
    const bib = doc.createElement('DIV');
    bib.id = 'abt-smart-bib';
    bib.className = 'noselect mceNonEditable';

    if (options.heading) {
        const heading = doc.createElement('H3');
        heading.innerText = options.heading;
        if (options.style) heading.className = 'toggle';
        bib.appendChild(heading);
    }

    for (const meta of bibliography) {
        const item = doc.createElement('DIV');
        item.id = meta.id;
        item.innerHTML = meta.html;
        bib.appendChild(item);
    }

    const noCitationsWithHeading: boolean = bib.children.length === 1 && options.heading !== null;
    const noCitationsWithoutHeading: boolean = bib.children.length === 0;

    if (existingBib) existingBib.parentElement.removeChild(existingBib);
    if (noCitationsWithHeading || noCitationsWithoutHeading) return;

    // Save a reference to the current cursor location
    const selection = editor.selection;
    const cursor = editor.dom.create('span', { id: 'CURSOR', class: 'abt_cite'});
    selection.getNode().appendChild(cursor);

    // Do work
    editor.setContent(editor.getContent() + bib.outerHTML);

    // Move cursor back to where it was & delete reference
    const el = editor.dom.doc.getElementById('CURSOR');
    if (el) {
        editor.selection.select(el, true);
        editor.selection.collapse(true);
        el.parentElement.removeChild(el);
    }
}
