
type CiteTypeArray = { label: string, value: CSL.CitationType, inUse: boolean }[];

export const CitationTypeArray: CiteTypeArray = [
    { label: 'Bill', value: 'bill', inUse: true },
    { label: 'Book', value: 'book', inUse: true },
    { label: 'Book Section', value: 'chapter', inUse: true },
    { label: 'Case', value: 'legal_case', inUse: true },
    { label: 'Conference Proceeding', value: 'paper-conference', inUse: true },
    { label: 'Generic', value: 'article', inUse: true },
    { label: 'Encyclopedia Entry', value: 'entry-encyclopedia', inUse: true },
    { label: 'Film', value: 'motion_picture', inUse: true },
    { label: 'Hearing', value: 'speech', inUse: true },
    { label: 'Journal Article', value: 'article-journal', inUse: true },
    { label: 'Magazine Article', value: 'article-magazine', inUse: true },
    { label: 'Newspaper Article', value: 'article-newspaper', inUse: true },
    { label: 'Patent', value: 'patent', inUse: true },
    { label: 'Report', value: 'report', inUse: true },
    { label: 'Statute', value: 'legislation', inUse: true },
    { label: 'Thesis', value: 'thesis', inUse: true },
    { label: 'Television Broadcast', value: 'broadcast', inUse: true },
    { label: 'Web Page', value: 'webpage', inUse: true },

    { label: 'Book - Review', value: 'review-book', inUse: false },
    { label: 'Dataset', value: 'dataset', inUse: false },
    { label: 'Entry - Generic', value: 'entry', inUse: false },
    { label: 'Entry - Dictionary', value: 'entry-dictionary', inUse: false },
    { label: 'Figure', value: 'figure', inUse: false },
    { label: 'Graphic', value: 'graphic', inUse: false },
    { label: 'Interview', value: 'interview', inUse: false },
    { label: 'Manuscript', value: 'manuscript', inUse: false },
    { label: 'Map', value: 'map', inUse: false },
    { label: 'Music - Musical Score', value: 'musical_score', inUse: false },
    { label: 'Music - Song', value: 'song', inUse: false },
    { label: 'Pamphlet', value: 'pamphlet', inUse: false },
    { label: 'Personal Communication', value: 'personal_communication', inUse: false },
    { label: 'Post', value: 'post', inUse: false },
    { label: 'Review', value: 'review', inUse: false },
    { label: 'Treaty', value: 'treaty', inUse: false },
    { label: 'Website - Blog', value: 'post-weblog', inUse: false },
];




export const FieldMappings = {
    bill: {
        title: 'Bill',
        relevant: [
            'bill',
            'chapter-number',
            'page',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'Code Pages',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Legislative Body',
            'Number',
            'Publication',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ],
    },
    book: {
        title: 'Book',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ],
    },
    chapter: {
        title: 'Book Section',
        relevant: [
            'chapter',
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Book',
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ],
    },
    'legal_case': {
        title: 'Case',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision',
            'Sections',
            'Short',
            'Title',
            'Volume',
        ],
    },
    'paper-conference': {
        title: 'Conference Proceeding',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Proc',
            'Publisher',
            'Revision',
            'Sections',
            'Short',
            'Title',
            'Volume',
        ],
    },
    article: {
        title: 'Generic',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'number',
            'page',
            'container-title',
            'publisher',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Number',
            'Pages',
            'Publication',
            'Publisher',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ],
    },
    'entry-encyclopedia': {
        title: 'Encyclopedia Entry',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'container-title',
            'genre',
            'ISBN',
            'issue',
            'page',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Encyclopedia',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    'motion_picture': {
        title: 'Film',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'publisher',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Distributor',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    speech: {
        title: 'Hearing',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    'article-journal': {
        title: 'Journal Article',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'container-title',
            'page',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Journal',
            'Pages',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    'article-magazine': {
        title: 'Magazine Article',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    'article-newspaper': {
        title: 'Newspaper Article',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    patent: {
        title: 'Patent',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'publisher',
            'number',
            'page',
            'section',
            'shortTitle',
            'container-title',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Issuer',
            'Number',
            'Pages',
            'Sections',
            'Short Title',
            'Source',
            'Title',
            'Volume',
        ]
    },
    report: {
        title: 'Report',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'number',
            'page',
            'container-title',
            'publisher',
            'section',
            'volume',
            'shortTitle',
            'title',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Number',
            'Pages',
            'Publication',
            'Publisher',
            'Sections',
            'Series Volume',
            'Short Title',
            'Title',
        ]
    },
    legislation: {
        title: 'Statute',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'section',
            'shortTitle',
            'publisher',
            'number',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Sections',
            'Short Title',
            'Source',
            'Statute Number',
            'Title',
            'Volume',
        ]
    },
    thesis: {
        title: 'Thesis',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    broadcast: {
        title: 'Television Broadcast',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'publisher',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Distributor',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
    webpage: {
        title: 'Web Page',
        relevant: [
            'chapter-number',
            'DOI',
            'accessed',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'page',
            'container-title',
            'publisher',
            'number',
            'section',
            'shortTitle',
            'title',
            'volume',
        ],
        label: [
            'Chapter',
            'DOI',
            'Date Accessed',
            'Edition',
            'Genre',
            'ISBN',
            'Issue',
            'Pages',
            'Publication',
            'Publisher',
            'Revision Number',
            'Sections',
            'Short Title',
            'Title',
            'Volume',
        ]
    },
}
