
type CiteTypeArray = { label: string, value: CSL.CitationType, inUse: boolean }[];

export const CitationTypeArray: CiteTypeArray = [
    { label: 'Bill', value: 'bill', inUse: true },
    { label: 'Book', value: 'book', inUse: true },
    { label: 'Book Section', value: 'chapter', inUse: true },
    { label: 'Case', value: 'legal_case', inUse: true },
    { label: 'Conference Proceeding', value: 'paper-conference', inUse: true },
    { label: 'Encyclopedia Entry', value: 'entry-encyclopedia', inUse: true },
    { label: 'Film', value: 'motion_picture', inUse: true },
    { label: 'Hearing', value: 'speech', inUse: true },
    { label: 'Journal Article', value: 'article-journal', inUse: true },
    { label: 'Magazine Article', value: 'article-magazine', inUse: true },
    { label: 'Newspaper Article', value: 'article-newspaper', inUse: true },
    { label: 'Patent', value: 'patent', inUse: true },
    { label: 'Report', value: 'report', inUse: true },
    { label: 'Statute', value: 'legislation', inUse: true },
    { label: 'Thesis', value: 'thesis', inUse: true },
    { label: 'Television Broadcast', value: 'broadcast', inUse: true },
    { label: 'Web Page', value: 'webpage', inUse: true },

    { label: 'Book - Review', value: 'review-book', inUse: false },
    { label: 'Dataset', value: 'dataset', inUse: false },
    { label: 'Entry - Generic', value: 'entry', inUse: false },
    { label: 'Entry - Dictionary', value: 'entry-dictionary', inUse: false },
    { label: 'Figure', value: 'figure', inUse: false },
    { label: 'Generic', value: 'article', inUse: false },
    { label: 'Graphic', value: 'graphic', inUse: false },
    { label: 'Interview', value: 'interview', inUse: false },
    { label: 'Manuscript', value: 'manuscript', inUse: false },
    { label: 'Map', value: 'map', inUse: false },
    { label: 'Music - Musical Score', value: 'musical_score', inUse: false },
    { label: 'Music - Song', value: 'song', inUse: false },
    { label: 'Pamphlet', value: 'pamphlet', inUse: false },
    { label: 'Personal Communication', value: 'personal_communication', inUse: false },
    { label: 'Post', value: 'post', inUse: false },
    { label: 'Review', value: 'review', inUse: false },
    { label: 'Treaty', value: 'treaty', inUse: false },
    { label: 'Website - Blog', value: 'post-weblog', inUse: false },
];

export const FieldMappings = {
    bill: {
        title: 'Bill',
        relevant: [
            'title',
            'number',
            'page',
            'volume',
            'section',
            'publisher',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Bill Number',
            'Code Pages',
            'Code Volume',
            'Section',
            'Legislative Body',
            'Date',
            'Date Accessed',
        ],
    },
    book: {
        title: 'Book',
        relevant: [
            'title',
            'collection-title',
            'collection-number',
            'number-of-pages',
            'volume',
            'number-of-volumes',
            'edition',
            'publisher',
            'publisher-place',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Series Title',
            'Series Number',
            '# of Pages',
            'Volume',
            '# of Volumes',
            'Edition',
            'Publisher',
            'Publisher Location',
            'Date',
            'Date Accessed',
        ],
    },
    chapter: {
        title: 'Book Section',
        relevant: [
            'title',
            'container-title',
            'chapter-number',
            'collection-title',
            'collection-number',
            'volume',
            'number-of-volumes',
            'edition',
            'publisher',
            'publisher-place',
            'issued',
            'accessed',
            'page',
            'ISBN',
        ],
        label: [
            'Section Title',
            'Book Title',
            'Chapter Number',
            'Series',
            'Series Number',
            'Volume',
            '# of Volumes',
            'Edition',
            'Publisher',
            'Publisher Location',
            'Date',
            'Date Accessed',
            'Pages',
            'ISBN',
        ],
    },
    'legal_case': {
        title: 'Case',
        relevant: [
            'title',
            'authority',
            'number',
            'issued',
            'accessed',
        ],
        label: [
            'Case Name',
            'Court',
            'Docket Number',
            'Date',
            'Access Date',
        ],
    },
    'paper-conference': {
        title: 'Conference Proceeding',
        relevant: [
            'title',
            'event',
            'event-place',
            'event-date',
        ],
        label: [
            'Title',
            'Conference Name',
            'Conference Location',
            'Date',
        ],
    },
    'entry-encyclopedia': {
        title: 'Encyclopedia Entry',
        relevant: [
            'title',
            'container-title',
            'collection-title',
            'collection-number',
            'volume',
            'number-of-volumes',
            'edition',
            'publisher',
            'publisher-place',
            'page',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Encyclopedia Title',
            'Series',
            'Series Number',
            'Volume',
            '# of Volumes',
            'Edition',
            'Publisher',
            'Publisher Location',
            'Pages',
            'Date',
            'Access Date',
        ]
    },
    'motion_picture': {
        title: 'Film',
        relevant: [
            'title',
            'publisher',
            'genre',
            'language',
            'medium',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Distributor',
            'Genre',
            'language',
            'Format',
            'Date',
            'Date Accessed',
        ]
    },
    speech: {
        title: 'Presentation',
        relevant: [
            'title',
            'event',
            'event-place',
            'language',
        ],
        label: [
            'Title',
            'Event Name',
            'Event Location',
            'Language',
        ]
    },
    'article-journal': {
        title: 'Journal Article',
        relevant: [
            'title',
            'container-title',
            'journalAbbreviation',
            'volume',
            'issue',
            'page',
            'DOI',
            'URL',
            'issued',
        ],
        label: [
            'Title',
            'Journal',
            'Journal Abbreviation',
            'Volume',
            'Issue',
            'Pages',
            'DOI',
            'URL',
            'Date',
        ]
    },
    'article-magazine': {
        title: 'Magazine Article',
        relevant: [
            'title',
            'container-title',
            'volume',
            'issue',
            'page',
            'ISSN',
            'URL',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Magazine',
            'Volume',
            'Issue',
            'Pages',
            'ISSN',
            'URL',
            'Date',
            'Date Accessed',
        ]
    },
    'article-newspaper': {
        title: 'Newspaper Article',
        relevant: [
            'title',
            'container-title',
            'section',
            'page',
            'issue',
            'URL',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Publication',
            'Section',
            'Pages',
            'Issue',
            'URL',
            'Date',
            'Access Date',
        ]
    },
    patent: {
        title: 'Patent',
        relevant: [
            'title',
            'number',
            'jurisdiction',
            'page',
            'publisher',
            'issued',
            'accessed',

            'chapter-number',
            'DOI',
            'edition',
            'genre',
            'ISBN',
            'issue',
            'section',
            'shortTitle',
            'container-title',
            'volume',
        ],
        label: [
            'Title',
            'Number',
            'Jurisdiction',
            'Pages',
            'Issuer',
            'Date',
            'Date Accessed',
        ]
    },
    report: {
        title: 'Report',
        relevant: [
            'title',
            'number',
            'collection-title',
            'container-title',
            'publisher',
            'page',
            'URL',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Number',
            'Series',
            'Publication',
            'Publisher',
            'Pages',
            'URL',
            'Date',
            'Date Accessed',
        ]
    },
    legislation: {
        title: 'Statute',
        relevant: [
            'title',
            'number',
            'section',
            'page',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Statute Number',
            'Section',
            'Pages',
            'Date',
            'Date Accessed',
        ]
    },
    thesis: {
        title: 'Thesis',
        relevant: [
            'title',
            'number-of-pages',
            'publisher',
            'publisher-place',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            '# of Pages',
            'University',
            'Location',
            'Date',
            'Date Accessed',
        ]
    },
    broadcast: {
        title: 'Television Broadcast',
        relevant: [
            'title',
            'container-title',
            'number',
            'medium',
            'publisher',
            'issued',
            'accessed',
        ],
        label: [
            'Title',
            'Program Title',
            'Episode Number',
            'Format',
            'Network',
            'Date',
            'Date Accessed',
        ]
    },
    webpage: {
        title: 'Web Page',
        relevant: [
            'title',
            'container-title',
            'issued',
            'accessed',
            'URL',
        ],
        label: [
            'Content Title',
            'Website Title',
            'Date Published',
            'Date Accessed',
            'URL',
        ]
    },
}
